// <auto-generated />
using System;
using Caisse.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Caisse.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240204124809_DateSeedingTwo")]
    partial class DateSeedingTwo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Caisse.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "High-Tech"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Electroménager"
                        });
                });

            modelBuilder.Entity("Caisse.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CategorieId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PicturePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Price")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Quantite")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.ToTable("Produits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategorieId = 1,
                            Description = "Pire Arnaque du siècle",
                            Nom = "Iphone 15",
                            PicturePath = "",
                            Price = 1300,
                            Quantite = 10
                        },
                        new
                        {
                            Id = 2,
                            CategorieId = 1,
                            Description = "Super téléphone",
                            Nom = "Iphone 12",
                            PicturePath = "",
                            Price = 500,
                            Quantite = 120
                        },
                        new
                        {
                            Id = 3,
                            CategorieId = 1,
                            Description = "Lave plus blanc que blanc",
                            Nom = "Machine à laver",
                            PicturePath = "",
                            Price = 500,
                            Quantite = 5
                        });
                });

            modelBuilder.Entity("Caisse.Models.Produit", b =>
                {
                    b.HasOne("Caisse.Models.Categorie", "Categorie")
                        .WithMany("ListProduit")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("Caisse.Models.Categorie", b =>
                {
                    b.Navigation("ListProduit");
                });
#pragma warning restore 612, 618
        }
    }
}
